const data = {
  cast: [
    {
      adult: false,
      gender: 1,
      id: 1134684,
      known_for_department: "Acting",
      name: "Park Eun-bin",
      original_name: "Park Eun-bin",
      popularity: 26.03,
      profile_path: "/fpMeZG7En6BUfNPNGmzZqJWKlCM.jpg",
      character: "Woo Young-woo",
      credit_id: "624e6234d19a3300a6bcd4c4",
      order: 0,
    },
    {
      adult: false,
      gender: 2,
      id: 1565392,
      known_for_department: "Acting",
      name: "Kang Tae-oh",
      original_name: "Kang Tae-oh",
      popularity: 19.584,
      profile_path: "/aMenmaLlcK6YMZnN7NBvvaVuq4O.jpg",
      character: "Lee Jun-ho",
      credit_id: "624e63d7e86017006714b3f2",
      order: 1,
    },
    {
      adult: false,
      gender: 2,
      id: 1648169,
      known_for_department: "Acting",
      name: "Kang Ki-young",
      original_name: "Kang Ki-young",
      popularity: 10.166,
      profile_path: "/bZKB6fXWS7mBWoOBsXlLx0P36hJ.jpg",
      character: "Jung Myeong-seok",
      credit_id: "624e67975ca704006514f233",
      order: 2,
    },
    {
      adult: false,
      gender: 2,
      id: 1572347,
      known_for_department: "Acting",
      name: "Jeon Bae-soo",
      original_name: "Jeon Bae-soo",
      popularity: 10.471,
      profile_path: "/3jH7s2IUz7sgRRYlrd0soBfA8PE.jpg",
      character: "Woo Gwang-ho",
      credit_id: "62be0c3a0372640167b88b1b",
      order: 3,
    },
    {
      adult: false,
      gender: 1,
      id: 2720442,
      known_for_department: "Acting",
      name: "Baek Ji-won",
      original_name: "Baek Ji-won",
      popularity: 7.804,
      profile_path: "/dKt6fEOXsCQddqGuFdpLcwsgBBp.jpg",
      character: "Han Seon-young",
      credit_id: "62be0c757304b523856c9a7b",
      order: 4,
    },
    {
      adult: false,
      gender: 1,
      id: 560070,
      known_for_department: "Acting",
      name: "Jin Kyung",
      original_name: "Jin Kyung",
      popularity: 16.286,
      profile_path: "/eKw4YbLw0LWkTCn6wbTiKkRltc2.jpg",
      character: "Tae Su-mi",
      credit_id: "624e67ece86017006714c674",
      order: 5,
    },
    {
      adult: false,
      gender: 1,
      id: 1579819,
      known_for_department: "Acting",
      name: "Ha Yoon-kyung",
      original_name: "Ha Yoon-kyung",
      popularity: 12.239,
      profile_path: "/px90PTsY0mHnsK4ffAdNCk9JiLy.jpg",
      character: "Choi Su-yeon",
      credit_id: "62be0c8866469a0137bbaf55",
      order: 6,
    },
    {
      adult: false,
      gender: 2,
      id: 2839957,
      known_for_department: "Acting",
      name: "Joo Jong-hyuk",
      original_name: "Joo Jong-hyuk",
      popularity: 9.109,
      profile_path: "/dm5GdHE4gN3YIbgziBIHwJmJmEX.jpg",
      character: "Kwon Min-woo",
      credit_id: "624e67e19e458600501ed652",
      order: 7,
    },
    {
      adult: false,
      gender: 1,
      id: 2790041,
      known_for_department: "Acting",
      name: "Joo Hyun-young",
      original_name: "Joo Hyun-young",
      popularity: 7.215,
      profile_path: "/pdRddCz7U43f5rUzovbzKtRu6YP.jpg",
      character: "Dong Geu-ra-mi",
      credit_id: "624e67bde263bb0064a2ada0",
      order: 8,
    },
    {
      adult: false,
      gender: 2,
      id: 2240033,
      known_for_department: "Acting",
      name: "Im Sung-jae",
      original_name: "Im Sung-jae",
      popularity: 2.6,
      profile_path: "/ggrfTvymOhQNxTqR63KXajQ1GIT.jpg",
      character: "Kim Min-sik",
      credit_id: "62be0de29512e1007c40d563",
      order: 9,
    },
  ],
  crew: [
    {
      adult: false,
      gender: 2,
      id: 1920791,
      known_for_department: "Directing",
      name: "Yoo In-sik",
      original_name: "Yoo In-sik",
      popularity: 2.516,
      profile_path: "/6zbLpK1wRWySvpNx0KimiH1KNN6.jpg",
      credit_id: "624e68f71b157d004fdfdb53",
      department: "Directing",
      job: "Director",
    },
    {
      adult: false,
      gender: 1,
      id: 2201125,
      known_for_department: "Writing",
      name: "Moon Ji-won",
      original_name: "Moon Ji-won",
      popularity: 0.648,
      profile_path: "/97N2tT1rp6soDObDAE2JNWi1ozP.jpg",
      credit_id: "624e6902d2b2090067101fca",
      department: "Writing",
      job: "Writer",
    },
    {
      adult: false,
      gender: 0,
      id: 2327591,
      known_for_department: "Production",
      name: "Lee Sang-baek",
      original_name: "Lee Sang-baek",
      popularity: 0.98,
      profile_path: null,
      credit_id: "62c59247dcb6a300501ad6d2",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      gender: 1,
      id: 3664617,
      known_for_department: "Sound",
      name: "Roh Young-sim",
      original_name: "Roh Young-sim",
      popularity: 0.982,
      profile_path: null,
      credit_id: "62fa1fd0e267de007eb8aa2b",
      department: "Sound",
      job: "Music Supervisor",
    },
    {
      adult: false,
      gender: 0,
      id: 2779067,
      known_for_department: "Editing",
      name: "Um Tae-shick",
      original_name: "Um Tae-shick",
      popularity: 0.6,
      profile_path: null,
      credit_id: "63d27ebae72fe800aa0235ef",
      department: "Editing",
      job: "Digital Colorist",
    },
  ],
  id: 197067,
};

console.log(data.cast.length);
console.log(data.crew.length);
